### ISSUE TITLE
Update to use conversations_list

### ISSUE THREAD

**Issue by malvidin** [NMRbox/slacklogger#1]
The following uses the current API endpoint of conversations.list, instead of the deprecated channels.list.  It also includes both public and private channels, and permits use of the channel name or the channel ID. 
```
response = self.client.conversations_list(types="public_channel,private_channel")
if response['ok']:
    channels = response['channels']
    channel_search = [c for c in channels if channel_name in (c['id'], c['name'])]
```
https://github.com/NMRbox/slacklogger/blob/36db627a35ccd0bf6deeb48b52978c677eac9399/nmrbox_slack/slacklogger.py#L29

**Comment by Gerardwx** [comment]
Update applied.
